"""Add basic vehicle types

Revision ID: 955c2e32b42b
Revises: 0e127e43b578
Create Date: 2024-10-25 11:49:19.774357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955c2e32b42b'
down_revision = '0e127e43b578'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diesel_locos',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('low_fuel', sa.Boolean(), server_default='TRUE',
                    nullable=False
            ),
            sa.ForeignKeyConstraint(['id'], ['vehicles.id'],
                    name=op.f('fk_diesel_locos_id_vehicles')
            ),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_diesel_locos'))
    )
    op.create_table('electric_locos',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('electric_break', sa.Boolean(), server_default='FALSE',
                    nullable=False
            ),
            sa.ForeignKeyConstraint(['id'], ['vehicles.id'],
                    name=op.f('fk_electric_locos_id_vehicles')
            ),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_electric_locos'))
    )
    op.create_table('steam_locos',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('boiler_emtpy', sa.Boolean(), server_default='TRUE',
                    nullable=False
            ),
            sa.Column('check_leakage', sa.Boolean(), server_default='TRUE',
                    nullable=False
            ),
            sa.ForeignKeyConstraint(['id'], ['vehicles.id'],
                    name=op.f('fk_steam_locos_id_vehicles')
            ),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_steam_locos'))
    )
    op.add_column('vehicles', sa.Column('type', sa.Text(), nullable=False,
                server_default='vehicle'))
    op.add_column('vehicles', sa.Column('state', sa.Text(), nullable=False,
                server_default='unknown'))
    op.add_column('vehicles', sa.Column('station', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('track', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('space', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles') as batch_op:
        batch_op.drop_column('space')
        batch_op.drop_column('track')
        batch_op.drop_column('station')
        batch_op.drop_column('state')
        batch_op.drop_column('type')
    op.drop_table('steam_locos')
    op.drop_table('electric_locos')
    op.drop_table('diesel_locos')
    # ### end Alembic commands ###
