"""Add vehicles table

Revision ID: 5ec76e1b3aba
Revises: 932be86c57d5
Create Date: 2024-09-04 13:46:07.513083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec76e1b3aba'
down_revision = '932be86c57d5'
branch_labels = None
depends_on = None

ENGINES = [
    {
        'name': 'Ed 3/3',
        'number': 401,
        'nvr': '90 85 0008 541-4',
        'token': 'lok401',
        'given_name': 'Bauma',
        'short_name': '401'
    }, {
        'name': 'E 3/3',
        'number': 8518,
        'nvr': '90 85 0008 518-2',
        'token': 'lok18',
        'given_name': 'Bäretswil',
        'short_name': '8518'
    }, {
        'name': 'BT Eb 3/5',
        'number': 9,
        'nvr': '90 85 0005 889-0',
        'token': 'lok9',
        'given_name': None,
        'short_name': 'Lok 9'
    }, {
        'name': 'Ed 3/4',
        'number': 2,
        'nvr': '90 85 0007 422-8',
        'token': 'lok2',
        'given_name': 'Hinwil',
        'short_name': 'Lok 2'
    }, {
        'name': 'Ed 3/3',
        'number': 4,
        'nvr': '90 85 0008 674-3',
        'token': 'lok4',
        'given_name': 'Schwyz',
        'short_name': 'Lok 4'
    }, {
        'name': 'Ee 3/3',
        'number': 16363,
        'nvr': None,
        'token': 'ee33',
        'given_name': None,
        'short_name': None
    }, {
        'name': 'BT Be 4/4',
        'number': 15,
        'nvr': None,
        'token': None,
        'given_name': None,
        'short_name': 'BT 15'
    }, {
        'name': 'Tm III',
        'number': 9529,
        'nvr': None,
        'token': 'tmiii',
        'given_name': None,
        'short_name': 'Tm'
    }, {
        'name': 'Tem III',
        'number': 354,
        'nvr': None,
        'token': 'temiii',
        'given_name': None,
        'short_name': 'Tem'
    }, {
        'name': 'Tm II',
        'number': 93,
        'nvr': None,
        'token': None,
        'given_name': None,
        'short_name': None
    }
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    vehicles = op.create_table('vehicles',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.Text(), nullable=False),
            sa.Column('number', sa.Integer(), nullable=True),
            sa.Column('nvr', sa.Text(), nullable=True),
            sa.Column('token', sa.Text(), nullable=True),
            sa.Column('given_name', sa.Text(), nullable=True),
            sa.Column('short_name', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
            sa.UniqueConstraint('token', name=op.f('uq_vehicles_token')))
    op.bulk_insert(vehicles, ENGINES)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
