"""Add vehicle relation to workday table

Revision ID: 0bb3f0dd7228
Revises: 5ec76e1b3aba
Create Date: 2024-09-04 15:11:51.025232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb3f0dd7228'
down_revision = '5ec76e1b3aba'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workdays') as batch_op:
        batch_op.add_column(
                sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
                op.f('fk_workdays_vehicle_id_vehicles'),
                'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workdays') as batch_op:
        batch_op.drop_constraint(
                op.f('fk_workdays_vehicle_id_vehicles'), type_='foreignkey')
        batch_op.drop_column('vehicle_id')
    # ### end Alembic commands ###
