"""Add vehicle manager table

Revision ID: 6f342ee09ce3
Revises: 0bb3f0dd7228
Create Date: 2024-09-12 14:32:23.162809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f342ee09ce3'
down_revision = '0bb3f0dd7228'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_managers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('badge_color', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vehicle_managers_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_managers')),
        sa.UniqueConstraint('user_id', name=op.f('uq_vehicle_managers_user_id')))
    with op.batch_alter_table('vehicles') as batch_op:
        batch_op.add_column(
                sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
                op.f('fk_vehicles_manager_id_vehicle_managers'),
                'vehicle_managers', ['manager_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles') as batch_op:
        batch_op.drop_constraint(
                op.f('fk_vehicles_manager_id_vehicle_managers'), type_='foreignkey')
        batch_op.drop_column('manager_id')
    op.drop_table('vehicle_managers')
    # ### end Alembic commands ###
