"""Add state for workdays

Revision ID: f8e53f94cdc9
Revises: 955c2e32b42b
Create Date: 2024-12-06 13:54:22.793378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e53f94cdc9'
down_revision = '955c2e32b42b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workdays', sa.Column('state', sa.Text(), server_default='draft', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workdays', 'state')
    # ### end Alembic commands ###
