"""Add archived flag for user, workday and vehicle

Revision ID: f7bbf9edf925
Revises: f8e53f94cdc9
Create Date: 2025-08-22 16:07:18.461697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bbf9edf925'
down_revision = 'f8e53f94cdc9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('vehicles', sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('workdays', sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workdays', 'archived')
    op.drop_column('vehicles', 'archived')
    op.drop_column('users', 'archived')
    # ### end Alembic commands ###
